default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

development:
  <<: *default
  database: myexchange_development

test:
  <<: *default
  database: myexchange_test

production:
  <<: *default
  database: myexchange_production
  username: myexchange
  password: <%= ENV['MYEXCHANGE_DATABASE_PASSWORD'] %>
